config/routes.rb
Rails.application.routes.draw do
  root "welcome#index"
  get '/logout', to: 'sessions#destroy'
  get '/auth/instagram/callback', to: 'sessions#create'
  get '/dashboard', to: "users#show"
  get '/feed', to: "instagram#feed"
  get '/search', to: "instagram#search"
  get '/trending', to: "instagram#trend"
end

app/models/user.rb
class User < ActiveRecord::Base
  def self.find_or_create_from_auth(auth)
    user = User.find_or_create_by(provider: auth.provider, uid: auth.uid)
      user.email     = auth.info.email
      user.nickname  = auth.info.nickname
      user.image     = auth.info.image
      user.token     = auth.credentials.token if auth.credentials
      user.save
    return user
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  helper_method :current_user, :current_client

  def current_user
    @current_user ||= current_client.user if current_client
  end

  def current_client
    if session[:user_id]
      user = User.find(session[:user_id])
      @current_client ||= Instagram.client(access_token: user.token)
    end
  end

  def authorize!
    redirect_to root_path unless current_user
  end
end

app/controllers/instagram_controller.rb
class InstagramController < ApplicationController
  def feed
    @posts = current_client.user_media_feed({count: 100}).paginate(page: params[:page], per_page: 9)
  end

  def search
    if params[:search] == ""
      redirect_to feed_path
    else
      tags = current_client.tag_search(params[:search])
      redirect_to feed_path if !tags[0]
      @posts = current_client.tag_recent_media(tags[0].name).paginate(page: params[:page], per_page: 9)
    end
  end

  def trend
    @posts = current_client.media_popular({count: 100}).paginate(page: params[:page], per_page: 9)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    user = User.find_or_create_from_auth(oauth_data)
    session[:user_id] = user.id
    redirect_to dashboard_path
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path
  end

  private
  def oauth_data
    request.env['omniauth.auth']
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/instagram/feed.html.erb
<header id="feed-back">
</header>
<div class="container-feed ">
  <%= will_paginate @posts %>
  <div class="row">
    <% @posts.each do |item| %>
    <% if item.caption %>
    <div class="col">
      <ul id="thumbnail">
        <button data-toggle="modal" data-target="#myModal-<%=item.id%>">
          <li id="image"><%= image_tag item.images.low_resolution.url%></li>
          <li>Likes: <%= item.likes[:count] %></li>
        </button>
      </ul>
    </div>
    <%= render partial: "partials/modal", locals: {item: item}%>
    <% end %>
    <% end %>
  </div>
</div>

app/views/instagram/feed.js.erb
$('#my-posts').append('<%=j render partial: "partials/posts", locals: {posts: @posts}%>');
<% if @posts.next_page %>
  $('.pagination').replaceWith('<%= j will_paginate @posts %>');
<% else %>
  $(window).off('scroll');
  $('.pagination').remove();
<% end %>

app/views/instagram/search.html.erb
<header id="feed-back">
</header>
<div class="container-feed ">
  <div id="search">
    <%= render partial: "partials/search"%>
  </div>
  <%= will_paginate @posts %>
  <div class="row">
    <% @posts.each do |item| %>
    <% if item.caption %>
    <div class="col">
      <ul id="thumbnail">
        <button data-toggle="modal" data-target="#myModal-<%=item.id%>">
          <li id="image"><%= image_tag item.images.low_resolution.url%></li>
          <li>Likes: <%= item.likes[:count] %></li>
        </button>
      </ul>
    </div>
    <%= render partial: "partials/modal", locals: {item: item}%>
    <% end %>
    <% end %>
  </div>
</div>

app/views/instagram/trend.html.erb
<header id="feed-back">
</header>
<div class="container-feed ">
  <div id="search">
    <%= render partial: "partials/search"%>
  </div>
  <%= will_paginate @posts %>
  <div class="row">
    <% @posts.each do |item| %>
    <% if item.caption %>
    <div class="col">
      <ul id="thumbnail">
        <button data-toggle="modal" data-target="#myModal-<%=item.id%>">
          <li id="image"><%= image_tag item.images.low_resolution.url%></li>
          <li>Likes: <%= item.likes[:count] %></li>
        </button>
      </ul>
    </div>
    <%= render partial: "partials/modal", locals: {item: item}%>
    <% end %>
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Instapic</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link href="font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css">
  <link href="http://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic" rel="stylesheet" type="text/css">
  <link href="http://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet" type="text/css">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">
</head>
<body>
  <%= render partial: "partials/nav" %>
  <%= yield %>
</body>
</html>

app/views/partials/_modal.html.erb
<div class="modal fade" id="myModal-<%=item.id%>" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
          <h4 id="username_big"><%= item.caption.from.username %></h4>
          <%= image_tag item.user.profile_picture, height:'60', width:'60', class:"profile-pic-medium" %>
      </div>
      <div class="modal-body">
        <hr class="star-primary">
        <img src="<%= item.images.standard_resolution.url %>" class="img-responsive img-centered" alt="">
        <div class="large-4 columns">
          <p id="likes"><%= item.likes["count"] %> likes</p>
          <div id="comments">
          <% item.comments.data.each do |comment| %>
          <strong id="username"><%= comment.from.username %></strong>  <%= comment.text %><br>
          <% end %>
        </div>
        </div>
        <br>
        <br>
        <button type="button" class="btn btn-default" data-dismiss="modal"><i class="fa fa-times"></i> Close</button>
      </div>
    </div>
  </div>
</div>

app/views/partials/_nav.html.erb
<nav class="navbar navbar-custom navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <a class="navbar-brand page-scroll" href="/">
        <i class="fa fa-instagram"></i>  <span class="light">Insta</span> Pic
      </a>
    </div>
    <div class="navbar-right">
      <ul class="nav navbar-nav">
        <% if current_user.nil? %>
        <li>
          <a class="page-scroll" href="#login">Login</a>
        </li>
        <% else %>
        <li>
          <%= image_tag current_user.profile_picture , class: "nav-image" %>
        </li>
        <li >
          <%= link_to current_user.username , dashboard_path, class: "page-scroll" %></a>
        </li>
        <li>
          <%= link_to "Logout", logout_path %>
        </li>
        <li>
          <%= link_to "Browse", feed_path %>
        </li>
        <li>
          <%= link_to "Trending", trending_path %>
        </li>
        <% end %>
        <li>
          <a class="page-scroll" href="#contact">Contact</a>
        </li>
      </ul>
    </div>
  </div>
</nav>

app/views/partials/_posts.html.erb
<% posts.each do |post| %>
<% if post.caption %>
<tr class="post">
  <td><%= image_tag post.images.low_resolution.url%>></td>
</tr>
<% end %>
<% end %>

<!-- <% posts.each do |item| %>
<% if item.caption %>
<div class="col">
<ul id="thumbnail">
<button data-toggle="modal" data-target="#myModal-<%=item.id%>">
<li id="image"><%= image_tag item.images.low_resolution.url%></li>
<li>Likes: <%= item.likes[:count] %></li>
</button>
</ul>
</div>
<%= render partial: "partials/modal", locals: {item: item}%>
<% end %>
<% end %> -->

app/views/partials/_search.html.erb
<div class="form-group" id="tag-search">
  <%= form_tag("/search", method: "get") do%>
    <%= label_tag :search, "" %>
    <%= text_field_tag :search, nil, class: 'form-control', placeholder: 'search #tags' %>
    <%= submit_tag "", class: 'hidden', method: "get", value: 'search-tags' %>
  <% end %>
</div>

app/views/users/show.html.erb
<header class="intro dashboard">
  <div class="intro-body">
    <p class="intro-text" id="welcome">Welcome back, <%= current_user.username %><br></p>
  </div>
</header>
<div class="container-feed">
  <div class="pictures">
    <div class="row">
      <% current_client.user_recent_media.each do |item| %>
      <% if item.caption %>
      <div class="col">
        <ul id="thumbnail">
          <button data-toggle="modal" data-target="#myModal-<%=item.id%>">
            <li id="image"><%= image_tag item.images.low_resolution.url%></li>
            <li>Likes: <%= item.likes[:count] %></li>
          </button>
        </ul>
      </div>
      <%= render partial: "partials/modal", locals: {item: item}%>
      <% end %>
      <% end %>
    </div>
  </div>
</div>

app/views/welcome/index.html.erb
<header class="intro">
  <div class="intro-body">
    <div class="container">
      <div class="row">
        <div class="col-md-8 col-md-offset-2">
          <h1 class="brand-heading">InstaPic</h1>
          <p class="intro-text">An instagram clone<br></p>
          <%  if current_user.nil? %>
          <div class="btn btn-circle page-scroll">
          <%= link_to "", "#login", class:  "fa fa-instagram"%>
          <div>
            <% end %>
        </div>
      </div>
    </div>
  </div>
</header>
<% if current_user.nil? %>
<section id="login" class="container content-section text-center">
  <div class="row">
    <div class="col-lg-8 col-lg-offset-2">
      <h2>Login With Your Instagram Account</h2>
      <%= link_to "Login", "auth/instagram", class: "btn btn-default btn-lg" %>
    </div>
  </div>
</section>
<% end %>
<div class="container text-center">
  <footer id="contact" class="container content-section text-center">
    <div class="row">

        <h2>Contact Mitch Ashby</h2>
        <p><a href="mailto:mitchashby16@gmail.com">mitchashby16@gmail.com</a>
        </p>
        <ul class="list-inline banner-social-buttons">
          <li>
            <%= link_to "GitHub", "http://www.github.com/mitchashby16", class: "btn btn-default btn-lg" %>
          </li>
          <li>
            <%= link_to "LinkedIn", "http://www.linkedin.com/in/mitchashby", class: "btn btn-default btn-lg" %>
          </li>
        </ul>

    </div>
<br>
<br>
      <p>Copyright &copy; InstaPic 2015</p>
  </div>

</footer>